# Required for login
login = 'login'
password = 'password'

# To avoid getting captcha blocked the bot needs to make breaks between transactions
timeout = 2  # minutes
buying_spree = 4

# Is the bot meant to buy items for credit net gain?
buy_for_credits = True
minimum_gain_per_item = 30000  # Low minimum value can lead to high inventory clutter

# Is the bot meant to automatically sell items bought for credit gain?
automatic_sale = False

# List items which bot is meant to actively auction for and the maximum bet
active_bet = [
    ('MCB-25', 100000),
    ('MCB-50', 100000),
    ('SAB-50', 100000),
    ('PLT-3030', 100000),
    ('PLT-2021', 100000),
    ('ACM-1', 20000),
    ('Napęd G3N-7900', 800000),
    ('Osłona SG3N-B02', 4000000),
    ('Moduł maskujący typ A', 25000),
    ('CPU maskujące', 0),
    ('CPU maskujące XL', 0),
    ('Slot-CPU 2', 0),
    ('Slot-CPU 3', 0),
    ('Slot-CPU 4', 0),
    ('CPU auto-rakiety', 0),
    ('CPU turbo-mina 2', 0),
    ('CPU skokowy 2', 0),
    ('CPU Radar', 0),
    ('CPU naprawiający drony 2', 0),
    ('CPU amunicyjny', 0),
    ('Smartbomb-CPU', 0),
    ('CPU - stabilna osłona', 0),
    ('CPU ulepszające generatory', 0),
    ('Robot naprawiający 3', 0),
    ('Robot naprawiający 4', 0),
    ('Ulepszone CPU skoków 1', 0),
    ('CPU rakietowy', 0),
    ('CPU wspomagające wyrzutnię rakiet', 0),
    ('CPU pomagający w namierzaniu 2', 0),
    ('Turbo rakietowe', 0),
    ('CPU Autonaprawa', 0),
    ('CPU laboratoryjny', 0),
    ('Powiększenie ładowni', 0),
    ('LF-3', 7000000),
    ('Wyrzutnia rakietowa Hellstorm 2', 0),
    ('Xenomit', 0),
    ('CDD', 1000000),
    ('Iris', 10000000),
    ('Powielacz punktów doświadczenia', 100000),
    ('Wzmacniacz osłony', 100000),
    ('Powielacz szkód', 100000),
    ('Przyśpieszacz naprawy', 100000),
    ('Powielacz poważania', 100000),
    ('Przyśpieszacz regeneracji osłony', 100000),
    ('Powielacz surowców', 100000),
    ('Powielacz hitpoints', 100000),
    ('Aegis', 0),
    ('Aegis Elite', 0),
    ('Aegis Veteran', 0),
    ('Citadel', 0),
    ('Citadel Elite', 0),
    ('Citadel Veteran', 0),
    ('Spearhead', 0),
    ('Spearhead Elite', 0),
    ('Spearhead Veteran', 0),
    ('Moduł: poszycie', 0),
    ('Moduł: deflektor', 0),
    ('Moduł powielacza poważania', 0),
    ('Moduł powielacza doświadczenia', 0),
    ('Moduł powielacza szkód', 0),
    ('Moduł: naprawa', 0),
    ('Moduł: laser LR', 0),
    ('Moduł: laser MR', 0),
    ('Moduł: laser HR', 0),
    ('Moduł: rakiety LA', 0),
    ('Moduł: rakiety MA', 0),
    ('Vengeance Lightning', 0),
    ('Diminisher', 0),
    ('Sentinel', 0),
    ('Solace', 0),
    ('Spectrum', 0),
    ('Venom', 0)
]

list_of_all_items = [
    'MCB-25',
    'MCB-50',
    'SAB-50',
    'PLT-3030',
    'PLT-2021',
    'ACM-1',
    'Napęd G3N-7900',
    'Osłona SG3N-B02',
    'Moduł maskujący typ A',
    'CPU maskujące',
    'CPU maskujące XL',
    'Slot-CPU 2',
    'Slot-CPU 3',
    'Slot-CPU 4',
    'CPU auto-rakiety',
    'CPU turbo-mina 2',
    'CPU skokowy 2',
    'CPU Radar',
    'CPU naprawiający drony 2',
    'CPU amunicyjny',
    'Smartbomb-CPU',
    'CPU - stabilna osłona',
    'CPU ulepszające generatory',
    'Robot naprawiający 3',
    'Robot naprawiający 4',
    'Ulepszone CPU skoków 1',
    'CPU rakietowy',
    'CPU wspomagające wyrzutnię rakiet',
    'CPU pomagający w namierzaniu 2',
    'Turbo rakietowe',
    'CPU Autonaprawa',
    'CPU laboratoryjny',
    'Powiększenie ładowni',
    'LF-3',
    'Wyrzutnia rakietowa Hellstorm 2',
    'Xenomit',
    'CDD',
    'Iris',
    'Powielacz punktów doświadczenia',
    'Wzmacniacz osłony',
    'Powielacz szkód',
    'Przyśpieszacz naprawy',
    'Powielacz poważania',
    'Przyśpieszacz regeneracji osłony',
    'Powielacz surowców',
    'Powielacz hitpoints',
    'Aegis',
    'Aegis Elite',
    'Aegis Veteran',
    'Citadel',
    'Citadel Elite',
    'Citadel Veteran',
    'Spearhead',
    'Spearhead Elite',
    'Spearhead Veteran',
    'Moduł: poszycie',
    'Moduł: deflektor',
    'Moduł powielacza poważania',
    'Moduł powielacza doświadczenia',
    'Moduł powielacza szkód',
    'Moduł: naprawa',
    'Moduł: laser LR',
    'Moduł: laser MR',
    'Moduł: laser HR',
    'Moduł: rakiety LA',
    'Moduł: rakiety MA',
    'Vengeance Lightning',
    'Diminisher',
    'Sentinel',
    'Solace',
    'Spectrum',
    'Venom'
]
